### ISSUE TITLE
Cannot add_pub_key using couchdb

### ISSUE THREAD

**Issue by Bazm0** [davedoesdev/pub-keystore#1]
Hi, I have configured pub-keystore on aws hosted docker container with couchdb. 
Any time I try to add a new pub_key I get the following error:

_add_pub_key error: %s name=CouchError, message=forbidden: not allowed to edit the database, error=forbidden, reason=not allowed to edit the database, server=CouchDB/1.6.1 (Erlang OTP/R15B01), date=Tue, 06 Jan 2015 10:48:41 GMT, content-type=text/plain; charset=utf-8, content-length=66, cache-control=must-revalidate, status=403_

Tried configuring with a couchdb admin username/password and without - same issue occurs. I can add couchdb dbs and insert values using the command line, any idea what's going on with this?

**Comment by davedoesdev** [comment]
Hi @Bazm0 
You passed `username` and `password` in the `config` object right?
Your user will need to have the `DB_NAME-updater` role, where `DB_NAME` is the name of the database (defaults to `pub-keys` so your user needs to have the `pub-keys-updater` role).
Let me know if that helps...
David

**Comment by davedoesdev** [comment]
(I just noticed I didn't put that in the docs - sorry)
EDIT: updated docs, fixed a test fail

**Comment by Bazm0** [comment]
Cheers @davedoesdev, username and password were passed, will try using the role update.

**Comment by davedoesdev** [comment]
@Bazm0 did that work?

**Comment by Bazm0** [comment]
Yeah, roles issue on CouchDB. Cheers.
